require: rubocop-rspec

Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/AsciiComments:
  Enabled: false # 日本語コメント
Style/Documentation:
  Enabled: false # ドキュメント
RSpec/ContextWording:
  Enabled: false # 日本語が想定されていないため
